# Generated by Django 4.1.7 on 2023-06-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="first_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="driver", old_name="first_name", new_name="name",
        ),
        migrations.RemoveField(model_name="customer", name="last_name",),
        migrations.RemoveField(model_name="driver", name="last_name",),
    ]
