# Generated by Django 4.2.2 on 2023-07-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_first_name_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contact_no",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postcode",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="driver",
            name="D_O_B",
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name="driver",
            name="contact_no",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="driver",
            name="licence_no",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_no",
            field=models.IntegerField(),
        ),
    ]
