# Generated by Django 4.2.2 on 2023-07-01 10:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_alter_customer_contact_no_alter_customer_postcode_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="customer",
            name="time",
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(default="prefer not to say", max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="customer",
            name="drop_off_loc",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pick_up_loc",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="gender",
            field=models.CharField(default="prefer not to say", max_length=10),
        ),
    ]
