# Generated by Django 4.2.2 on 2023-07-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_customer_user_alter_driver_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="postcode",
        ),
    ]
