# Generated by Django 4.2.2 on 2023-07-07 10:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_remove_customer_postcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rent_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("number", models.IntegerField()),
                ("pin", models.IntegerField()),
                ("location", models.CharField(max_length=200)),
                ("dateBooked", models.DateTimeField(default=datetime.datetime.now)),
                ("timeDuration", models.CharField(max_length=20)),
                ("startTime", models.DateTimeField(default=datetime.datetime.now)),
                ("dateCreated", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-dateCreated"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("number", models.IntegerField()),
                ("pin", models.IntegerField()),
                ("location", models.CharField(max_length=200)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
